package com.example.yodelit.test;

import java.util.ArrayList;

import android.test.ActivityInstrumentationTestCase2;
import android.util.Log;

import com.example.yodelit.AddEchoActivity;
import com.example.yodelit.EchoVotes;
import com.example.yodelit.YodelitController;

import junit.framework.TestCase;

public class EchoVotesTest extends ActivityInstrumentationTestCase2<AddEchoActivity>  {

	//what to do if the test passes
	public void testPass(){
		assertTrue(true);
	}
	
	//list of user ids that have been upvoted
	public ArrayList<String> upgoatList = new ArrayList<String>();
	
	//list of user ids that have been downvotes
	private ArrayList<String> downgoatList = new ArrayList<String>(); 
	
	//autogenerated method to remove errors
	public EchoVotesTest(Class<AddEchoActivity> EchoVotes) {
		super(EchoVotes);
		// TODO Auto-generated constructor stub
	}

	//checks for user downvotes
	public void addUserDownVote() {
		try {
			this.downgoatList.add(YodelitController.getActiveUser().getUname());
			testPass();
		} catch (IllegalArgumentException e){
			assertEquals("No downgoats created", e.getMessage());
		}
	}
	
	//checks for user upvotes
	public void addUserUpVote(){
		try {
			this.upgoatList.add(YodelitController.getActiveUser().getUname());
			testPass();
		} catch (IllegalArgumentException e){
			assertEquals("No upgoats created", e.getMessage());
		}
	}
}
